export DATABASE_NAME=image-db
export DATABASE_DIALECT=postgres
export DATABASE_PORT=5432
export DATABASE_PASSWORD=
export DATABASE_USERNAME=image-man
export DATABASE_HOST=localhost
export DB_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
